### PR TITLE
feat: re: Hotfix titlebar; also handle race condition 

### PR DESCRIPTION
**Pull request by p0lygun**

### CODE REVIEW

**Comment by noahlias** [comment]
when i run it, the title bar seems right. but the size seem error
image
this is the mac, later i will test in the windows

**Comment by noahlias** [comment]
in windows, it is ok
image

**Comment by p0lygun** [comment]
What error on Mac ??

**Comment by noahlias** [comment]
> What error on Mac ??

it can't minimize and I will test it again tonight, maybe my laptop is 13 inc?

**Comment by p0lygun** [comment]
There is no button to minimize or the button is not working?

**Comment by noahlias** [comment]
It takes up half of the screen, and I can't move it to another area.
I can't see the minimize button, and maybe the problem of Monitor Resolution.
I will make a Screen Recording Gif tonight, It's ok in windows,

**Comment by p0lygun** [comment]
Hmmm really wired, ok then let's wait till tonight before merging this

**Comment by noahlias** [comment]
Kapture 2022-07-27 at 18 55 09
the first issue is it can't move
Kapture 2022-07-27 at 19 01 07
the second issue is the minimize button doesn't work

**Comment by p0lygun** [comment]
Ok then I will push a fix to disable custom titlebar on mac

**Comment by p0lygun** [comment]
What about windows all good ?

**Comment by noahlias** [comment]
yeah, on windows all good

**Review by noahlias — DISMISSED** [review]

**Comment by p0lygun** [comment]
@noahlias test again and then approve

**Review by noahlias — APPROVED** [review]
image
it works

**Pull request merged**
