### PR TITLE
feat: add User profile

### PR DESCRIPTION
**Pull request by p0lygun**

### CODE REVIEW

**Comment by noahlias** [comment]
the layout need to fix.
image
add chat seem too close to the next 
image
this copy id didn't work

**Comment by noahlias** [comment]
it works in windows, only Mac is hurt. hmmm
image

**Comment by p0lygun** [comment]
Hmmm weird

**Comment by p0lygun** [comment]
I guess we let mac be like that ?
We don't have that much time to fix it 
Lets just make sure windows and Linux work

**Review by noahlias — DISMISSED** [review]

**Comment by noahlias** [comment]
I agree.

**Review by noahlias — APPROVED** [review]

**Review by noahlias — DISMISSED** [review]

**Comment by noahlias** [comment]
sorry, I am doing something wrong about Merge which makes the lint error, I have fixed it to the original.

**Comment by p0lygun** [comment]
No worries, I'll merge it

**Comment by p0lygun** [comment]
@noahlias merge is already merged ?

**Comment by p0lygun** [comment]
approve changes

**Comment by noahlias** [comment]
sorry, I use the update branch with merge commit which causes the lint error. I should use the rebase.

**Review by noahlias — APPROVED** [review]

**Comment by p0lygun** [comment]
u merge it

**Pull request merged**
